[package]
name = "finitechat-darkmatter"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cgka-engine.workspace = true
cgka-traits.workspace = true
serde.workspace = true
transport-http-server.workspace = true
