[package]
name = "finitechat-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "finitechat-darkmatter"
path = "src/main.rs"

[dependencies]
cgka-traits.workspace = true
finitechat-darkmatter = { path = "../finitechat-darkmatter" }
finitechat-proto = { path = "../finitechat-proto" }
finitechat-server = { path = "../finitechat-server" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
transport-http-server.workspace = true
